<?php
// 1. Start Output Buffering to capture the template HTML
ob_start();

include '../../BackEnd/config/dbconfig.php';

$supplier_id = isset($_GET['supplier_id']) ? (int) $_GET['supplier_id'] : 0;

if ($supplier_id <= 0) {
    die("Invalid supplier ID.");
}

$stmt = mysqli_prepare($conn, "
    SELECT s.*, t.template_folder 
    FROM suppliers s
    JOIN templates t ON s.template_id = t.template_id
    WHERE s.supplier_id = ?
    ");

if (!$stmt) {
    die("Database query preparation failed: " . mysqli_error($conn));
}

mysqli_stmt_bind_param($stmt, "i", $supplier_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
$supplier = mysqli_fetch_assoc($result);
mysqli_stmt_close($stmt);

if (!$supplier) {
    die("Supplier not found.");
}

$template_path = "../templates/" . $supplier['template_folder'] . "/index.php";

if (file_exists($template_path)) {
    include($template_path);
} else {
    die("Template not found: " . htmlspecialchars($template_path));
}

// 2. Get the content generated by the included template
$page_content = ob_get_clean();

// 3. Define the Loader HTML, CSS, and JS
$loader_html = '
<div id="global-loading-screen">
    <div class="spinner-wrapper">
        <div class="spinner">
            <div></div><div></div><div></div><div></div><div></div><div></div>
        </div>
        <div class="spinner2">
            <div></div><div></div><div></div><div></div><div></div><div></div>
        </div>
    </div>
</div>';

$loader_css = '
<style>
    /* Full Screen Overlay */
    #global-loading-screen {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #1a1a1a; /* Dark background to make spinners pop */
        z-index: 9999999;
        display: flex;
        justify-content: center;
        align-items: center;
        transition: opacity 0.6s ease-out, visibility 0.6s;
    }

    /* Hide class for JS */
    #global-loading-screen.loaded {
        opacity: 0;
        visibility: hidden;
        pointer-events: none;
    }

    /* Center wrapper for the absolute spinners */
    .spinner-wrapper {
        position: relative;
        width: 0;
        height: 0;
    }

    /* YOUR ORIGINAL CSS */
    .spinner {
        width: 16px;
        height: 16px;
        animation: spinner-y0fdc1 15s forwards infinite ease;
        position: absolute;
        top: 50%; left: 50%;
        margin-left: -8px; /* Center offset */
        margin-top: -8px;  /* Center offset */
        transform-style: preserve-3d;
    }

    .spinner > div {
        height: 100%;
        position: absolute;
        width: 100%;
        border: 1px solid #f8c828;
        background: rgba(248, 200, 40, 0.1); /* Slight fill for better visuals */
    }

    .spinner div:nth-of-type(1) { transform: translateZ(-8px) rotateY(180deg); }
    .spinner div:nth-of-type(2) { transform: rotateY(-270deg) translateX(50%); transform-origin: top right; }
    .spinner div:nth-of-type(3) { transform: rotateY(270deg) translateX(-50%); transform-origin: center left; }
    .spinner div:nth-of-type(4) { transform: rotateX(90deg) translateY(-50%); transform-origin: top center; }
    .spinner div:nth-of-type(5) { transform: rotateX(-90deg) translateY(50%); transform-origin: bottom center; }
    .spinner div:nth-of-type(6) { transform: translateZ(8px); }

    .spinner2 {
        width: 32px;
        height: 32px;
        animation: spinner-y0fdc2 15s forwards infinite ease;
        position: absolute;
        top: 50%; left: 50%;
        margin-left: -16px;
        margin-top: -16px;
        transform-style: preserve-3d;
    }

    .spinner2 > div {
        height: 100%;
        position: absolute;
        width: 100%;
        border: 1px solid #ffffff; /* Changed to white for contrast against dark bg */
    }

    .spinner2 div:nth-of-type(1) { transform: translateZ(-16px) rotateY(180deg); }
    .spinner2 div:nth-of-type(2) { transform: rotateY(-270deg) translateX(50%); transform-origin: top right; }
    .spinner2 div:nth-of-type(3) { transform: rotateY(270deg) translateX(-50%); transform-origin: center left; }
    .spinner2 div:nth-of-type(4) { transform: rotateX(90deg) translateY(-50%); transform-origin: top center; }
    .spinner2 div:nth-of-type(5) { transform: rotateX(-90deg) translateY(50%); transform-origin: bottom center; }
    .spinner2 div:nth-of-type(6) { transform: translateZ(16px); }

    @keyframes spinner-y0fdc1 {
        0% { transform: rotate(0deg) rotateX(0deg) rotateY(0deg); }
        24% { transform: rotate(0deg) rotateX(360deg) rotateY(360deg); width: 16px; height: 16px; }
        25% { transform: rotate(0deg) rotateX(360deg) rotateY(360deg); width: 48px; height: 48px; }
        50% { transform: rotate(225deg) rotateX(360deg) rotateY(360deg); width: 48px; height: 48px; }
        75% { transform: rotate(0deg) rotateX(360deg) rotateY(360deg); width: 48px; height: 48px; }
        76% { transform: rotate(0deg) rotateX(360deg) rotateY(360deg); width: 16px; height: 16px; }
        96% { transform: rotate(0deg) rotateX(0deg) rotateY(0deg); }
        100% { transform: rotate(0deg) rotateX(0deg) rotateY(0deg); }
    }

    @keyframes spinner-y0fdc2 {
        0% { transform: rotate(45deg) rotateX(0deg) rotateY(0deg); }
        24% { transform: rotate(45deg) rotateX(-360deg) rotateY(-360deg); width: 32px; height: 32px; }
        25% { transform: rotate(45deg) rotateX(-360deg) rotateY(-360deg); width: 48px; height: 48px; }
        50% { transform: rotate(-180deg) rotateX(-360deg) rotateY(-360deg); width: 48px; height: 48px; }
        75% { transform: rotate(45deg) rotateX(-360deg) rotateY(-360deg); width: 48px; height: 48px; }
        76% { transform: rotate(45deg) rotateX(-360deg) rotateY(-360deg); width: 32px; height: 32px; }
        96% { transform: rotate(45deg) rotateX(0deg) rotateY(0deg); }
        100% { transform: rotate(45deg) rotateX(0deg) rotateY(0deg); }
    }
</style>';

$loader_js = '
<script>
    // Wait for the entire page (images, scripts, styles) to load
    window.addEventListener("load", function() {
        var loader = document.getElementById("global-loading-screen");
        if(loader) {
            // Add the class that fades it out
            loader.classList.add("loaded");
            
            // Remove it from DOM after animation completes (optional)
            setTimeout(function(){
                loader.style.display = "none";
            }, 600);
        }
    });
</script>';

// 4. Inject logic: 
// Add CSS to <head>, HTML to start of <body>, JS to end of <body>.
// We use str_ireplace for case-insensitive replacement.

// Inject CSS before closing head tag
$final_content = str_ireplace('</head>', $loader_css . '</head>', $page_content);

// Inject Loader HTML immediately after opening body tag
$final_content = str_ireplace('<body>', '<body>' . $loader_html, $final_content);

// Inject JS before closing body tag
$final_content = str_ireplace('</body>', $loader_js . '</body>', $final_content);

// 5. Output the final HTML with the loader included
echo $final_content;

?>